initScript: "
    cd ${CONFIG_DIR};
    if ! test -f 'catch.hpp' ; then
        wget https://github.com/catchorg/Catch2/releases/download/v2.13.4/catch.hpp;
    fi;

    if ! test -f 'catch_main.o' ; then
        g++ -std=c++20 -c -I . catch_main.cpp -o catch_main.o;
    fi;
  "
studentIdRegex: .*?(\d+)\.zip
tasks:
  - name: "1"
    initScript: "
      cd ${PROJECT_DIR}/1/;
      if [ $? -ne 0 ]; then exit 1; fi;
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' . | xargs rm;
      for sourceFile in $(find . -type f); do
        sed -i 's/^.*<crtdbg.h>//g' $sourceFile;
        sed -i '1i #include <pollyfills.hpp>\n' $sourceFile;
      done;
      cp ${CONFIG_DIR}/unit_tests_1.cpp ${CONFIG_DIR}/pollyfills.* ${CONFIG_DIR}/catch_main.o ${CONFIG_DIR}/catch.hpp .;
      g++ -std=c++20 -I . catch_main.o *.cpp -o ${PROJECT_DIR}/units_tests_1;
    "
    testScript: "
      ${PROJECT_DIR}/units_tests_1 -r junit;
    "
    memoryScript: "
      cd ${PROJECT_DIR}/1/;
      ! valgrind ./units 2>&1 | grep 'LEAK SUMMARY';
    "
    memoryPoints: 0.8
  - name: "2"
    initScript: "
      cd ${PROJECT_DIR}/2/;
      if [ $? -ne 0 ]; then exit 1; fi;
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' . | xargs rm;
      for sourceFile in $(find . -type f); do
        sed -i 's/^.*<crtdbg.h>//g' $sourceFile;
        sed -i '1i #include <pollyfills.hpp>\n' $sourceFile;
      done;
      cp ${CONFIG_DIR}/unit_tests_2.cpp ${CONFIG_DIR}/pollyfills.* ${CONFIG_DIR}/catch_main.o ${CONFIG_DIR}/catch.hpp .;
      g++ -std=c++20 -I . catch_main.o *.cpp -o ${PROJECT_DIR}/units_tests_2;
    "
    testScript: "
      ${PROJECT_DIR}/units_tests_2 -r junit;
    "
    memoryScript: "
      cd ${PROJECT_DIR}/2/;
      ! valgrind ./units 2>&1 | grep 'LEAK SUMMARY';
    "
    memoryPoints: 1.2
