initScript: "
    cd ${CONFIG_DIR};
    if ! test -f 'catch.hpp' ; then
        wget https://github.com/catchorg/Catch2/releases/download/v2.13.4/catch.hpp;
    fi;

    if ! test -f 'unit_tests_1.o' ; then
        g++ -std=c++20 -c -I 1/ -I . unit_tests_1.cpp -o unit_tests_1.o;
    fi;

    if ! test -f 'unit_tests_2.o' ; then
        g++ -std=c++20 -c -I 2/ -I . unit_tests_2.cpp -o unit_tests_2.o;
    fi;
  "
studentIdRegex: .*?(\d+)\.zip
tasks:
  - name: "1"
    initScript: ""
    testScript: "
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' ${PROJECT_DIR}/1/ | xargs rm;
      find ${PROJECT_DIR}/1/ -type f | xargs sed -i 's/^.*<crtdbg.h>//g';
      cp ${CONFIG_DIR}/unit_tests_1.o ${PROJECT_DIR}/1/;
      g++ -std=c++20 ${PROJECT_DIR}/1/unit_tests_1.o ${PROJECT_DIR}/1/*.cpp -o ${PROJECT_DIR}/1/units;
      ${PROJECT_DIR}/1/units -r junit;
    "
    memoryScript: "
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' ${PROJECT_DIR}/1/ | xargs rm;
      find ${PROJECT_DIR}/1/ -type f | xargs sed -i 's/^.*<crtdbg.h>//g';
      cp ${CONFIG_DIR}/unit_tests_1.o ${PROJECT_DIR}/1/;
      g++ -std=c++20 ${PROJECT_DIR}/1/unit_tests_1.o ${PROJECT_DIR}/1/*.cpp -o ${PROJECT_DIR}/1/units;
      ! valgrind ${PROJECT_DIR}/1/units 2>&1 | grep 'LEAK SUMMARY';
    "
    memoryPoints: 0.8
  - name: "2"
    initScript: ""
    testScript: "
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' ${PROJECT_DIR}/2/ | xargs rm;
      find ${PROJECT_DIR}/2/ -type f | xargs sed -i 's/^.*<crtdbg.h>//g';
      cp ${CONFIG_DIR}/unit_tests_2.o ${PROJECT_DIR}/2/;
      g++ -std=c++20 ${PROJECT_DIR}/2/unit_tests_2.o ${PROJECT_DIR}/2/*.cpp -o ${PROJECT_DIR}/2/units;
      ${PROJECT_DIR}/2/units -r junit;
    "
    memoryScript: "
      grep -Prl '^\\s*(int|void)\\s*main\\(.*\\)' ${PROJECT_DIR}/2/ | xargs rm;
      find ${PROJECT_DIR}/2/ -type f | xargs sed -i 's/^.*<crtdbg.h>//g';
      cp ${CONFIG_DIR}/unit_tests_2.o ${PROJECT_DIR}/2/;
      g++ -std=c++20 ${PROJECT_DIR}/2/unit_tests_2.o ${PROJECT_DIR}/2/*.cpp -o ${PROJECT_DIR}/2/units;
      ! valgrind ${PROJECT_DIR}/2/units 2>&1 | grep 'LEAK SUMMARY';
    "
    memoryPoints: 1.2
